### ISSUE TITLE
Release not showing up in Installer

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/compact_forms#1]
Something isn't right with the latest release -- it's not showing up in the Installer. Maybe deleting and repackaging the latest release would solve it?

**Comment by klonos** [comment]
I remember that we had some issues with releases a while ago and 1.0.1 was releases back in May. Deleted and re-created the release on behalf of @BWPanda. This should fix things. Can you please check and let me know @laryn?

**Comment by ghost** [comment]
Closing for now. Re-open if this is still an issue.
