### ISSUE TITLE
Fields are always marked required

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/compact_forms#10]
Fields are always marked required, even if they are not required.

**Comment by laryn** [comment]
PR: https://github.com/backdrop-contrib/compact_forms/pull/11

**Comment by ghost** [comment]
Thanks @laryn, big oversight on my part :fearful: Small change requested in the PR before I can commit it.

**Comment by laryn** [comment]
@BWPanda Fixed.

**Comment by ghost** [comment]
Thanks @laryn, merged!
