### ISSUE TITLE
Support "all forms" and/or wildcards?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/compact_forms#12]
It would be nice to be able to have this compact form functionality apply to all new forms out of the box. There are a few ways that would make this simpler:

 - An "Apply to all forms" checkbox
 - An "Include/Exclude" option above the form IDs
 - The ability to use wildcards in the form IDs (e.g. `webform_client_form_*`)

**Comment by ghost** [comment]
Here's a PR if you care to test it @laryn: https://github.com/backdrop-contrib/compact_forms/pull/13

I figured wildcards were the easiest and most flexible solution, so went with that option.

**Comment by laryn** [comment]
@BWPanda LGTM 👍

**Comment by ghost** [comment]
Thanks @laryn. Committed and pushed a new release.
