### ISSUE TITLE
$.browser is removed from jQuery

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/compact_forms#2]
[These lines](https://github.com/backdrop-contrib/compact_forms/blob/1.x-1.x/js/compact_forms.js#L88-L90) cause a problem as [`$.browser` doesn't exist any more](http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed).

**Comment by ghost** [comment]
Here's the Drupal issue: https://www.drupal.org/node/2299969

**Comment by ghost** [comment]
Fixed: https://github.com/backdrop-contrib/compact_forms/commit/5cbec362f0ba34c942324d0dd781809cf807370b
