### ISSUE TITLE
Notice: Undefined index: #type in _compact_forms_process_fields()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/compact_forms#8]
I'm seeing this in the logs after upgrading to the latest version and clearing caches:

> Notice: Undefined index: #type in _compact_forms_process_fields() (line 123 of /path/modules/contrib/compact_forms/compact_forms.module).

**Comment by ghost** [comment]
@laryn Please try the linked PR and see if that works for you.

**Comment by laryn** [comment]
@BWPanda Yes, that seems to get rid of the notice. Thanks!

**Comment by ghost** [comment]
Thanks, committed.
